---
# Source: deploy/charts/deploy/templates/experiment.yaml
apiVersion: iter8.tools/v2alpha2
kind: Experiment
metadata:
  # the sha256sum suffix based on candidate is useful; it ensures that 
  # a new experiment is generated whenever the candidate version is updated 
  # (for example, by CD pipeline)
  name: hello-experiment
spec:
  # target should uniquely identify the application under experimentation
  target: hello
  strategy:
    # this is an SLO validation experiment
    testingPattern: Conformance
    actions:
      start:
      # ensure candidate service and deployment of the application are available
      - task: common/readiness 
        with:
          objRefs:
          - kind: Service
            name: hello-candidate
            namespace: NAMESPACE
          - kind: Deployment
            name: hello-candidate
            namespace: NAMESPACE
            waitFor: condition=available
      # collect Iter8's built-in metrics
      - task: metrics/collect
        with:
          time: "20s"
          versions:
          - name: new-version # this name must match the name of a version in versionInfo
            url: "http://hello-candidate.NAMESPACE:8080"
            qps: 8
  criteria:
    requestCount: iter8-system/request-count
    indicators:
    - iter8-system/error-count
    # service-level objectives (SLOs) that need to be satisfied by the new version
    # in order for it to be considered a winner
    objectives:
    - metric: iter8-system/mean-latency
      upperLimit: "500"
    - metric: iter8-system/error-rate
      upperLimit: "0.01"
    - metric: iter8-system/latency-95th-percentile
      upperLimit: "1000"
  duration:
    intervalSeconds: 1
    iterationsPerLoop: 1
  versionInfo:
    baseline:
      name: new-version
