apiVersion: iter8.tools/v2alpha2
kind: Experiment
metadata:
  name: hello-rollout-istio
spec:
  # target identifies the service under experimentation using its fully qualified name
  target: hello
  strategy:
    # this experiment will perform an A/B test
    testingPattern: Canary
    # this experiment will progressively shift traffic to the winning version
    deploymentPattern: Progressive
    actions:
      loop:
      # on each loop, send test traffic to all versions (for 10s)
      - task: metrics/collect
        with:
          time: 6s
          versions:
          - name: hello
            url: http://hello.NAMESPACE:8080
          - name: hello-candidate
            url: http://hello-candidate.NAMESPACE:8080
      # when the experiment completes, promote the winning version using kubectl apply
      finish:
      - if: CandidateWon()
        run: kubectl -n @<.Namespace>@ apply -f https://raw.githubusercontent.com/kalantar/iter8/cil-2/samples/cil/second/hello-candidate.yaml
      - if: not CandidateWon()
        run: kubectl -n @<.Namespace>@ apply -f https://raw.githubusercontent.com/kalantar/iter8/cil-2/samples/cil/second/hello.yaml
  criteria:
    objectives: # used for validating versions
    - metric: iter8-system/mean-latency
      upperLimit: 5
    - metric: iter8-system/error-rate
      upperLimit: "0.01"
    - metric: iter8-system/latency-95th-percentile
      upperLimit: 10
    requestCount: iter8-system/request-count
  duration: # product of fields determines length of the experiment
    intervalSeconds: 1
    iterationsPerLoop: 1
    maxLoops: 5
  versionInfo:
    # information about the app versions used in this experiment
    baseline:
      name: hello
      weightObjRef:
        apiVersion: networking.istio.io/v1beta1
        kind: VirtualService
        namespace: NAMESPACE
        name: hello
        fieldPath: .spec.http[1].route[0].weight
    candidates:
    - name: hello-candidate
      weightObjRef:
        apiVersion: networking.istio.io/v1beta1
        kind: VirtualService
        namespace: NAMESPACE
        name: hello
        fieldPath: .spec.http[1].route[1].weight

